### ISSUE TITLE
Switch default engine to "numpy"

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/flox#129]
This will let us support other array types more easily

For e.g. cupy does not support `ufunc.reduceat` https://docs.cupy.dev/en/stable/reference/ufunc.html

**Comment by ml31415** [comment]
I guess the default should remain, to pick the fastest implementation available. If cupy is available, that would probably mean to pick the numpy implementation for the functions available, otherwise, it should stick with the numba implementation. Also, transferring data forth and back to the GPU is some time overhead, that can not be neglected. I'm not sure, if it should better stay an active decision for the developer, to use the GPU and not something happening automatically.
